#!/usr/bin/php

<?php

	include_once 'jammu-instance';

	// sending message process
	if (strtolower(php_sapi_name()) == 'cli') {
		if (count($argv)) {
			if (isset($argv[1]) && isset($argv[2])) {
				// formating message
				$message = (object) ["address" => checkNumbers($argv[1]), "body" => $argv[2]];
				// sending message
				JammuI::sendMessage($message);
			}
			else {
				echo "\nParamètres pas complets !\n\n";
			}
		}
		else {
			echo "no args !";
		}
	}

	function checkNumbers($numberSource)
	{
		$value = $numberSource;

		if (preg_match("#path:#", $numberSource)) {
			$source = explode(':', $numberSource);
			if (file_exists(trim($source[1]))) {
				$numbers = explode("\n", file_get_contents($source[1]));
				return implode(',', $numbers);
			}
		}

		return $value;
	}